export const AppImages = {
    app_logo: require('./app_logo.png'),
    app_bg: require('./app_bg.png'),
    splash_image: require('./splash_logo.png'),
    horizontal_logo: require('./horizontal_logo.png'),
    header_img: require('./header_img.png'),
    banner_img: require('./banner_img.png'),
    service_one: require('./service_one.png'),
    service_two: require('./service_two.png'),
    service_three: require('./service_three.png'),
    consultant: require('./consultant.png'),
    pdf: require('./pdf_image.png'),
    service_bg: require('./service_bg.png'),
    file: require('./dummy.png'),
    userprofile: require('./userProfile.jpeg'),
};